[package]
name = "wasm-benchmark"
version = "0.1.0"
authors = ["Johan van Eck <jve.software@gmail.com>"]
description = "Rust Wasm vs JS benchmark"
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
